<?php
    
/**
 * The file that defines the API class
 *
 *
 * @link       https://www.grocrm.com/
 * @since      1.0.0
 *
 * @package    Grocrm
 * @subpackage Grocrm/api
 */

/**
 * The GroCRM API class.
 *
 * @since      1.0.0
 * @package    Grocrm
 * @subpackage Grocrm/api
 * @author     Gro CRM <support@grocrm.com>
 */
    
class GroCRM_API {
    
    const BASE_URL = "https://api.grocrm.com/v1/";
    
    private $token;
    
    public function __construct(string $token) {
        $this->token = $token;
    }
    
    public function getUser() {
        $args = [
            'headers' => [
                'Authorization' => 'Token '.$this->token,
            ]
        ];
        
        $url = self::BASE_URL."user";

        $response = wp_remote_get($url, $args);
        $statusCode = $response["response"]["code"];
        $body = $response["body"];
        $bodyArray = json_decode($body, true);
        
        if ($statusCode == 200) {
            return json_decode($body, true);
        } elseif (isset($bodyArray["message"])) {
            throw new \Exception($bodyArray["message"], $statusCode);
        } else {
            throw new \Exception("An error has occured. Please try again later.", $statusCode);
        }
    }
    
    public function getTimezones() {
        return [
            1 => esc_html__( 'Africa/Abidjan', 'grocrm'),
            2 => esc_html__( 'Africa/Accra', 'grocrm'),
            3 => esc_html__( 'Africa/Addis_Ababa', 'grocrm'),
            4 => esc_html__( 'Africa/Algiers', 'grocrm'),
            5 => esc_html__( 'Africa/Asmara', 'grocrm'),
            6 => esc_html__( 'Africa/Bamako', 'grocrm'),
            7 => esc_html__( 'Africa/Bangui', 'grocrm'),
            8 => esc_html__( 'Africa/Banjul', 'grocrm'),
            9 => esc_html__( 'Africa/Bissau', 'grocrm'),
            10 => esc_html__( 'Africa/Blantyre', 'grocrm'),
            11 => esc_html__( 'Africa/Brazzaville', 'grocrm'),
            12 => esc_html__( 'Africa/Bujumbura', 'grocrm'),
            13 => esc_html__( 'Africa/Cairo', 'grocrm'),
            14 => esc_html__( 'Africa/Casablanca', 'grocrm'),
            15 => esc_html__( 'Africa/Ceuta', 'grocrm'),
            16 => esc_html__( 'Africa/Conakry', 'grocrm'),
            17 => esc_html__( 'Africa/Dakar', 'grocrm'),
            18 => esc_html__( 'Africa/Dar_es_Salaam', 'grocrm'),
            19 => esc_html__( 'Africa/Djibouti', 'grocrm'),
            20 => esc_html__( 'Africa/Douala', 'grocrm'),
            21 => esc_html__( 'Africa/El_Aaiun', 'grocrm'),
            22 => esc_html__( 'Africa/Freetown', 'grocrm'),
            23 => esc_html__( 'Africa/Gaborone', 'grocrm'),
            24 => esc_html__( 'Africa/Harare', 'grocrm'),
            25 => esc_html__( 'Africa/Johannesburg', 'grocrm'),
            26 => esc_html__( 'Africa/Juba', 'grocrm'),
            27 => esc_html__( 'Africa/Kampala', 'grocrm'),
            28 => esc_html__( 'Africa/Khartoum', 'grocrm'),
            29 => esc_html__( 'Africa/Kigali', 'grocrm'),
            30 => esc_html__( 'Africa/Kinshasa', 'grocrm'),
            31 => esc_html__( 'Africa/Lagos', 'grocrm'),
            32 => esc_html__( 'Africa/Libreville', 'grocrm'),
            33 => esc_html__( 'Africa/Lome', 'grocrm'),
            34 => esc_html__( 'Africa/Luanda', 'grocrm'),
            35 => esc_html__( 'Africa/Lubumbashi', 'grocrm'),
            36 => esc_html__( 'Africa/Lusaka', 'grocrm'),
            37 => esc_html__( 'Africa/Malabo', 'grocrm'),
            38 => esc_html__( 'Africa/Maputo', 'grocrm'),
            39 => esc_html__( 'Africa/Maseru', 'grocrm'),
            40 => esc_html__( 'Africa/Mbabane', 'grocrm'),
            41 => esc_html__( 'Africa/Mogadishu', 'grocrm'),
            42 => esc_html__( 'Africa/Monrovia', 'grocrm'),
            43 => esc_html__( 'Africa/Nairobi', 'grocrm'),
            44 => esc_html__( 'Africa/Ndjamena', 'grocrm'),
            45 => esc_html__( 'Africa/Niamey', 'grocrm'),
            46 => esc_html__( 'Africa/Nouakchott', 'grocrm'),
            47 => esc_html__( 'Africa/Ouagadougou', 'grocrm'),
            48 => esc_html__( 'Africa/Porto-Novo', 'grocrm'),
            49 => esc_html__( 'Africa/Sao_Tome', 'grocrm'),
            50 => esc_html__( 'Africa/Tripoli', 'grocrm'),
            51 => esc_html__( 'Africa/Tunis', 'grocrm'),
            52 => esc_html__( 'Africa/Windhoek', 'grocrm'),
            53 => esc_html__( 'America/Adak', 'grocrm'),
            54 => esc_html__( 'America/Anchorage', 'grocrm'),
            55 => esc_html__( 'America/Anguilla', 'grocrm'),
            56 => esc_html__( 'America/Antigua', 'grocrm'),
            57 => esc_html__( 'America/Araguaina', 'grocrm'),
            58 => esc_html__( 'America/Argentina/Buenos_Aires', 'grocrm'),
            59 => esc_html__( 'America/Argentina/Catamarca', 'grocrm'),
            60 => esc_html__( 'America/Argentina/Cordoba', 'grocrm'),
            61 => esc_html__( 'America/Argentina/Jujuy', 'grocrm'),
            62 => esc_html__( 'America/Argentina/La_Rioja', 'grocrm'),
            63 => esc_html__( 'America/Argentina/Mendoza', 'grocrm'),
            64 => esc_html__( 'America/Argentina/Rio_Gallegos', 'grocrm'),
            65 => esc_html__( 'America/Argentina/Salta', 'grocrm'),
            66 => esc_html__( 'America/Argentina/San_Juan', 'grocrm'),
            67 => esc_html__( 'America/Argentina/San_Luis', 'grocrm'),
            68 => esc_html__( 'America/Argentina/Tucuman', 'grocrm'),
            69 => esc_html__( 'America/Argentina/Ushuaia', 'grocrm'),
            70 => esc_html__( 'America/Aruba', 'grocrm'),
            71 => esc_html__( 'America/Asuncion', 'grocrm'),
            72 => esc_html__( 'America/Atikokan', 'grocrm'),
            73 => esc_html__( 'America/Bahia', 'grocrm'),
            74 => esc_html__( 'America/Bahia_Banderas', 'grocrm'),
            75 => esc_html__( 'America/Barbados', 'grocrm'),
            76 => esc_html__( 'America/Belem', 'grocrm'),
            77 => esc_html__( 'America/Belize', 'grocrm'),
            78 => esc_html__( 'America/Blanc-Sablon', 'grocrm'),
            79 => esc_html__( 'America/Boa_Vista', 'grocrm'),
            80 => esc_html__( 'America/Bogota', 'grocrm'),
            81 => esc_html__( 'America/Boise', 'grocrm'),
            82 => esc_html__( 'America/Cambridge_Bay', 'grocrm'),
            83 => esc_html__( 'America/Campo_Grande', 'grocrm'),
            84 => esc_html__( 'America/Cancun', 'grocrm'),
            85 => esc_html__( 'America/Caracas', 'grocrm'),
            86 => esc_html__( 'America/Cayenne', 'grocrm'),
            87 => esc_html__( 'America/Cayman', 'grocrm'),
            88 => esc_html__( 'America/Chicago', 'grocrm'),
            89 => esc_html__( 'America/Chihuahua', 'grocrm'),
            90 => esc_html__( 'America/Costa_Rica', 'grocrm'),
            91 => esc_html__( 'America/Creston', 'grocrm'),
            92 => esc_html__( 'America/Cuiaba', 'grocrm'),
            93 => esc_html__( 'America/Curacao', 'grocrm'),
            94 => esc_html__( 'America/Danmarkshavn', 'grocrm'),
            95 => esc_html__( 'America/Dawson', 'grocrm'),
            96 => esc_html__( 'America/Dawson_Creek', 'grocrm'),
            97 => esc_html__( 'America/Denver', 'grocrm'),
            98 => esc_html__( 'America/Detroit', 'grocrm'),
            99 => esc_html__( 'America/Dominica', 'grocrm'),
            100 => esc_html__( 'America/Edmonton', 'grocrm'),
            101 => esc_html__( 'America/Eirunepe', 'grocrm'),
            102 => esc_html__( 'America/El_Salvador', 'grocrm'),
            103 => esc_html__( 'America/Fort_Nelson', 'grocrm'),
            104 => esc_html__( 'America/Fortaleza', 'grocrm'),
            105 => esc_html__( 'America/Glace_Bay', 'grocrm'),
            106 => esc_html__( 'America/Godthab', 'grocrm'),
            107 => esc_html__( 'America/Goose_Bay', 'grocrm'),
            108 => esc_html__( 'America/Grand_Turk', 'grocrm'),
            109 => esc_html__( 'America/Grenada', 'grocrm'),
            110 => esc_html__( 'America/Guadeloupe', 'grocrm'),
            111 => esc_html__( 'America/Guatemala', 'grocrm'),
            112 => esc_html__( 'America/Guayaquil', 'grocrm'),
            113 => esc_html__( 'America/Guyana', 'grocrm'),
            114 => esc_html__( 'America/Halifax', 'grocrm'),
            115 => esc_html__( 'America/Havana', 'grocrm'),
            116 => esc_html__( 'America/Hermosillo', 'grocrm'),
            117 => esc_html__( 'America/Indiana/Indianapolis', 'grocrm'),
            118 => esc_html__( 'America/Indiana/Knox', 'grocrm'),
            119 => esc_html__( 'America/Indiana/Marengo', 'grocrm'),
            120 => esc_html__( 'America/Indiana/Petersburg', 'grocrm'),
            121 => esc_html__( 'America/Indiana/Tell_City', 'grocrm'),
            122 => esc_html__( 'America/Indiana/Vevay', 'grocrm'),
            123 => esc_html__( 'America/Indiana/Vincennes', 'grocrm'),
            124 => esc_html__( 'America/Indiana/Winamac', 'grocrm'),
            125 => esc_html__( 'America/Inuvik', 'grocrm'),
            126 => esc_html__( 'America/Iqaluit', 'grocrm'),
            127 => esc_html__( 'America/Jamaica', 'grocrm'),
            128 => esc_html__( 'America/Juneau', 'grocrm'),
            129 => esc_html__( 'America/Kentucky/Louisville', 'grocrm'),
            130 => esc_html__( 'America/Kentucky/Monticello', 'grocrm'),
            131 => esc_html__( 'America/Kralendijk', 'grocrm'),
            132 => esc_html__( 'America/La_Paz', 'grocrm'),
            133 => esc_html__( 'America/Lima', 'grocrm'),
            134 => esc_html__( 'America/Los_Angeles', 'grocrm'),
            135 => esc_html__( 'America/Lower_Princes', 'grocrm'),
            136 => esc_html__( 'America/Maceio', 'grocrm'),
            137 => esc_html__( 'America/Managua', 'grocrm'),
            138 => esc_html__( 'America/Manaus', 'grocrm'),
            139 => esc_html__( 'America/Marigot', 'grocrm'),
            140 => esc_html__( 'America/Martinique', 'grocrm'),
            141 => esc_html__( 'America/Matamoros', 'grocrm'),
            142 => esc_html__( 'America/Mazatlan', 'grocrm'),
            143 => esc_html__( 'America/Menominee', 'grocrm'),
            144 => esc_html__( 'America/Merida', 'grocrm'),
            145 => esc_html__( 'America/Metlakatla', 'grocrm'),
            146 => esc_html__( 'America/Mexico_City', 'grocrm'),
            147 => esc_html__( 'America/Miquelon', 'grocrm'),
            148 => esc_html__( 'America/Moncton', 'grocrm'),
            149 => esc_html__( 'America/Monterrey', 'grocrm'),
            150 => esc_html__( 'America/Montevideo', 'grocrm'),
            151 => esc_html__( 'America/Montserrat', 'grocrm'),
            152 => esc_html__( 'America/Nassau', 'grocrm'),
            153 => esc_html__( 'America/New_York', 'grocrm'),
            154 => esc_html__( 'America/Nipigon', 'grocrm'),
            155 => esc_html__( 'America/Nome', 'grocrm'),
            156 => esc_html__( 'America/Noronha', 'grocrm'),
            157 => esc_html__( 'America/North_Dakota/Beulah', 'grocrm'),
            158 => esc_html__( 'America/North_Dakota/Center', 'grocrm'),
            159 => esc_html__( 'America/North_Dakota/New_Salem', 'grocrm'),
            160 => esc_html__( 'America/Ojinaga', 'grocrm'),
            161 => esc_html__( 'America/Panama', 'grocrm'),
            162 => esc_html__( 'America/Pangnirtung', 'grocrm'),
            163 => esc_html__( 'America/Paramaribo', 'grocrm'),
            164 => esc_html__( 'America/Phoenix', 'grocrm'),
            165 => esc_html__( 'America/Port-au-Prince', 'grocrm'),
            166 => esc_html__( 'America/Port_of_Spain', 'grocrm'),
            167 => esc_html__( 'America/Porto_Velho', 'grocrm'),
            168 => esc_html__( 'America/Puerto_Rico', 'grocrm'),
            169 => esc_html__( 'America/Rainy_River', 'grocrm'),
            170 => esc_html__( 'America/Rankin_Inlet', 'grocrm'),
            171 => esc_html__( 'America/Recife', 'grocrm'),
            172 => esc_html__( 'America/Regina', 'grocrm'),
            173 => esc_html__( 'America/Resolute', 'grocrm'),
            174 => esc_html__( 'America/Rio_Branco', 'grocrm'),
            175 => esc_html__( 'America/Santarem', 'grocrm'),
            176 => esc_html__( 'America/Santiago', 'grocrm'),
            177 => esc_html__( 'America/Santo_Domingo', 'grocrm'),
            178 => esc_html__( 'America/Sao_Paulo', 'grocrm'),
            179 => esc_html__( 'America/Scoresbysund', 'grocrm'),
            180 => esc_html__( 'America/Sitka', 'grocrm'),
            181 => esc_html__( 'America/St_Barthelemy', 'grocrm'),
            182 => esc_html__( 'America/St_Johns', 'grocrm'),
            183 => esc_html__( 'America/St_Kitts', 'grocrm'),
            184 => esc_html__( 'America/St_Lucia', 'grocrm'),
            185 => esc_html__( 'America/St_Thomas', 'grocrm'),
            186 => esc_html__( 'America/St_Vincent', 'grocrm'),
            187 => esc_html__( 'America/Swift_Current', 'grocrm'),
            188 => esc_html__( 'America/Tegucigalpa', 'grocrm'),
            189 => esc_html__( 'America/Thule', 'grocrm'),
            190 => esc_html__( 'America/Thunder_Bay', 'grocrm'),
            191 => esc_html__( 'America/Tijuana', 'grocrm'),
            192 => esc_html__( 'America/Toronto', 'grocrm'),
            193 => esc_html__( 'America/Tortola', 'grocrm'),
            194 => esc_html__( 'America/Vancouver', 'grocrm'),
            195 => esc_html__( 'America/Whitehorse', 'grocrm'),
            196 => esc_html__( 'America/Winnipeg', 'grocrm'),
            197 => esc_html__( 'America/Yakutat', 'grocrm'),
            198 => esc_html__( 'America/Yellowknife', 'grocrm'),
            199 => esc_html__( 'Antarctica/Casey', 'grocrm'),
            200 => esc_html__( 'Antarctica/Davis', 'grocrm'),
            201 => esc_html__( 'Antarctica/DumontDUrville', 'grocrm'),
            202 => esc_html__( 'Antarctica/Macquarie', 'grocrm'),
            203 => esc_html__( 'Antarctica/Mawson', 'grocrm'),
            204 => esc_html__( 'Antarctica/McMurdo', 'grocrm'),
            205 => esc_html__( 'Antarctica/Palmer', 'grocrm'),
            206 => esc_html__( 'Antarctica/Rothera', 'grocrm'),
            207 => esc_html__( 'Antarctica/Syowa', 'grocrm'),
            208 => esc_html__( 'Antarctica/Troll', 'grocrm'),
            209 => esc_html__( 'Antarctica/Vostok', 'grocrm'),
            210 => esc_html__( 'Arctic/Longyearbyen', 'grocrm'),
            211 => esc_html__( 'Asia/Aden', 'grocrm'),
            212 => esc_html__( 'Asia/Almaty', 'grocrm'),
            213 => esc_html__( 'Asia/Amman', 'grocrm'),
            214 => esc_html__( 'Asia/Anadyr', 'grocrm'),
            215 => esc_html__( 'Asia/Aqtau', 'grocrm'),
            216 => esc_html__( 'Asia/Aqtobe', 'grocrm'),
            217 => esc_html__( 'Asia/Ashgabat', 'grocrm'),
            218 => esc_html__( 'Asia/Baghdad', 'grocrm'),
            219 => esc_html__( 'Asia/Bahrain', 'grocrm'),
            220 => esc_html__( 'Asia/Baku', 'grocrm'),
            221 => esc_html__( 'Asia/Bangkok', 'grocrm'),
            222 => esc_html__( 'Asia/Barnaul', 'grocrm'),
            223 => esc_html__( 'Asia/Beirut', 'grocrm'),
            224 => esc_html__( 'Asia/Bishkek', 'grocrm'),
            225 => esc_html__( 'Asia/Brunei', 'grocrm'),
            226 => esc_html__( 'Asia/Chita', 'grocrm'),
            227 => esc_html__( 'Asia/Choibalsan', 'grocrm'),
            228 => esc_html__( 'Asia/Colombo', 'grocrm'),
            229 => esc_html__( 'Asia/Damascus', 'grocrm'),
            230 => esc_html__( 'Asia/Dhaka', 'grocrm'),
            231 => esc_html__( 'Asia/Dili', 'grocrm'),
            232 => esc_html__( 'Asia/Dubai', 'grocrm'),
            233 => esc_html__( 'Asia/Dushanbe', 'grocrm'),
            234 => esc_html__( 'Asia/Gaza', 'grocrm'),
            235 => esc_html__( 'Asia/Hebron', 'grocrm'),
            236 => esc_html__( 'Asia/Ho_Chi_Minh', 'grocrm'),
            237 => esc_html__( 'Asia/Hong_Kong', 'grocrm'),
            238 => esc_html__( 'Asia/Hovd', 'grocrm'),
            239 => esc_html__( 'Asia/Irkutsk', 'grocrm'),
            240 => esc_html__( 'Asia/Jakarta', 'grocrm'),
            241 => esc_html__( 'Asia/Jayapura', 'grocrm'),
            242 => esc_html__( 'Asia/Jerusalem', 'grocrm'),
            243 => esc_html__( 'Asia/Kabul', 'grocrm'),
            244 => esc_html__( 'Asia/Kamchatka', 'grocrm'),
            245 => esc_html__( 'Asia/Karachi', 'grocrm'),
            246 => esc_html__( 'Asia/Kathmandu', 'grocrm'),
            247 => esc_html__( 'Asia/Khandyga', 'grocrm'),
            248 => esc_html__( 'Asia/Kolkata', 'grocrm'),
            249 => esc_html__( 'Asia/Krasnoyarsk', 'grocrm'),
            250 => esc_html__( 'Asia/Kuala_Lumpur', 'grocrm'),
            251 => esc_html__( 'Asia/Kuching', 'grocrm'),
            252 => esc_html__( 'Asia/Kuwait', 'grocrm'),
            253 => esc_html__( 'Asia/Macau', 'grocrm'),
            254 => esc_html__( 'Asia/Magadan', 'grocrm'),
            255 => esc_html__( 'Asia/Makassar', 'grocrm'),
            256 => esc_html__( 'Asia/Manila', 'grocrm'),
            257 => esc_html__( 'Asia/Muscat', 'grocrm'),
            258 => esc_html__( 'Asia/Nicosia', 'grocrm'),
            259 => esc_html__( 'Asia/Novokuznetsk', 'grocrm'),
            260 => esc_html__( 'Asia/Novosibirsk', 'grocrm'),
            261 => esc_html__( 'Asia/Omsk', 'grocrm'),
            262 => esc_html__( 'Asia/Oral', 'grocrm'),
            263 => esc_html__( 'Asia/Phnom_Penh', 'grocrm'),
            264 => esc_html__( 'Asia/Pontianak', 'grocrm'),
            265 => esc_html__( 'Asia/Pyongyang', 'grocrm'),
            266 => esc_html__( 'Asia/Qatar', 'grocrm'),
            267 => esc_html__( 'Asia/Qyzylorda', 'grocrm'),
            268 => esc_html__( 'Asia/Rangoon', 'grocrm'),
            269 => esc_html__( 'Asia/Riyadh', 'grocrm'),
            270 => esc_html__( 'Asia/Sakhalin', 'grocrm'),
            271 => esc_html__( 'Asia/Samarkand', 'grocrm'),
            272 => esc_html__( 'Asia/Seoul', 'grocrm'),
            273 => esc_html__( 'Asia/Shanghai', 'grocrm'),
            274 => esc_html__( 'Asia/Singapore', 'grocrm'),
            275 => esc_html__( 'Asia/Srednekolymsk', 'grocrm'),
            276 => esc_html__( 'Asia/Taipei', 'grocrm'),
            277 => esc_html__( 'Asia/Tashkent', 'grocrm'),
            278 => esc_html__( 'Asia/Tbilisi', 'grocrm'),
            279 => esc_html__( 'Asia/Tehran', 'grocrm'),
            280 => esc_html__( 'Asia/Thimphu', 'grocrm'),
            281 => esc_html__( 'Asia/Tokyo', 'grocrm'),
            282 => esc_html__( 'Asia/Tomsk', 'grocrm'),
            283 => esc_html__( 'Asia/Ulaanbaatar', 'grocrm'),
            284 => esc_html__( 'Asia/Urumqi', 'grocrm'),
            285 => esc_html__( 'Asia/Ust-Nera', 'grocrm'),
            286 => esc_html__( 'Asia/Vientiane', 'grocrm'),
            287 => esc_html__( 'Asia/Vladivostok', 'grocrm'),
            288 => esc_html__( 'Asia/Yakutsk', 'grocrm'),
            289 => esc_html__( 'Asia/Yekaterinburg', 'grocrm'),
            290 => esc_html__( 'Asia/Yerevan', 'grocrm'),
            291 => esc_html__( 'Atlantic/Azores', 'grocrm'),
            292 => esc_html__( 'Atlantic/Bermuda', 'grocrm'),
            293 => esc_html__( 'Atlantic/Canary', 'grocrm'),
            294 => esc_html__( 'Atlantic/Cape_Verde', 'grocrm'),
            295 => esc_html__( 'Atlantic/Faroe', 'grocrm'),
            296 => esc_html__( 'Atlantic/Madeira', 'grocrm'),
            297 => esc_html__( 'Atlantic/Reykjavik', 'grocrm'),
            298 => esc_html__( 'Atlantic/South_Georgia', 'grocrm'),
            299 => esc_html__( 'Atlantic/St_Helena', 'grocrm'),
            300 => esc_html__( 'Atlantic/Stanley', 'grocrm'),
            301 => esc_html__( 'Australia/Adelaide', 'grocrm'),
            302 => esc_html__( 'Australia/Brisbane', 'grocrm'),
            303 => esc_html__( 'Australia/Broken_Hill', 'grocrm'),
            304 => esc_html__( 'Australia/Currie', 'grocrm'),
            305 => esc_html__( 'Australia/Darwin', 'grocrm'),
            306 => esc_html__( 'Australia/Eucla', 'grocrm'),
            307 => esc_html__( 'Australia/Hobart', 'grocrm'),
            308 => esc_html__( 'Australia/Lindeman', 'grocrm'),
            309 => esc_html__( 'Australia/Lord_Howe', 'grocrm'),
            310 => esc_html__( 'Australia/Melbourne', 'grocrm'),
            311 => esc_html__( 'Australia/Perth', 'grocrm'),
            312 => esc_html__( 'Australia/Sydney', 'grocrm'),
            313 => esc_html__( 'Europe/Amsterdam', 'grocrm'),
            314 => esc_html__( 'Europe/Andorra', 'grocrm'),
            315 => esc_html__( 'Europe/Astrakhan', 'grocrm'),
            316 => esc_html__( 'Europe/Athens', 'grocrm'),
            317 => esc_html__( 'Europe/Belgrade', 'grocrm'),
            318 => esc_html__( 'Europe/Berlin', 'grocrm'),
            319 => esc_html__( 'Europe/Bratislava', 'grocrm'),
            320 => esc_html__( 'Europe/Brussels', 'grocrm'),
            321 => esc_html__( 'Europe/Bucharest', 'grocrm'),
            322 => esc_html__( 'Europe/Budapest', 'grocrm'),
            323 => esc_html__( 'Europe/Busingen', 'grocrm'),
            324 => esc_html__( 'Europe/Chisinau', 'grocrm'),
            325 => esc_html__( 'Europe/Copenhagen', 'grocrm'),
            326 => esc_html__( 'Europe/Dublin', 'grocrm'),
            327 => esc_html__( 'Europe/Gibraltar', 'grocrm'),
            328 => esc_html__( 'Europe/Guernsey', 'grocrm'),
            329 => esc_html__( 'Europe/Helsinki', 'grocrm'),
            330 => esc_html__( 'Europe/Isle_of_Man', 'grocrm'),
            331 => esc_html__( 'Europe/Istanbul', 'grocrm'),
            332 => esc_html__( 'Europe/Jersey', 'grocrm'),
            333 => esc_html__( 'Europe/Kaliningrad', 'grocrm'),
            334 => esc_html__( 'Europe/Kiev', 'grocrm'),
            335 => esc_html__( 'Europe/Kirov', 'grocrm'),
            336 => esc_html__( 'Europe/Lisbon', 'grocrm'),
            337 => esc_html__( 'Europe/Ljubljana', 'grocrm'),
            338 => esc_html__( 'Europe/London', 'grocrm'),
            339 => esc_html__( 'Europe/Luxembourg', 'grocrm'),
            340 => esc_html__( 'Europe/Madrid', 'grocrm'),
            341 => esc_html__( 'Europe/Malta', 'grocrm'),
            342 => esc_html__( 'Europe/Mariehamn', 'grocrm'),
            343 => esc_html__( 'Europe/Minsk', 'grocrm'),
            344 => esc_html__( 'Europe/Monaco', 'grocrm'),
            345 => esc_html__( 'Europe/Moscow', 'grocrm'),
            346 => esc_html__( 'Europe/Oslo', 'grocrm'),
            347 => esc_html__( 'Europe/Paris', 'grocrm'),
            348 => esc_html__( 'Europe/Podgorica', 'grocrm'),
            349 => esc_html__( 'Europe/Prague', 'grocrm'),
            350 => esc_html__( 'Europe/Riga', 'grocrm'),
            351 => esc_html__( 'Europe/Rome', 'grocrm'),
            352 => esc_html__( 'Europe/Samara', 'grocrm'),
            353 => esc_html__( 'Europe/San_Marino', 'grocrm'),
            354 => esc_html__( 'Europe/Sarajevo', 'grocrm'),
            355 => esc_html__( 'Europe/Simferopol', 'grocrm'),
            356 => esc_html__( 'Europe/Skopje', 'grocrm'),
            357 => esc_html__( 'Europe/Sofia', 'grocrm'),
            358 => esc_html__( 'Europe/Stockholm', 'grocrm'),
            359 => esc_html__( 'Europe/Tallinn', 'grocrm'),
            360 => esc_html__( 'Europe/Tirane', 'grocrm'),
            361 => esc_html__( 'Europe/Ulyanovsk', 'grocrm'),
            362 => esc_html__( 'Europe/Uzhgorod', 'grocrm'),
            363 => esc_html__( 'Europe/Vaduz', 'grocrm'),
            364 => esc_html__( 'Europe/Vatican', 'grocrm'),
            365 => esc_html__( 'Europe/Vienna', 'grocrm'),
            366 => esc_html__( 'Europe/Vilnius', 'grocrm'),
            367 => esc_html__( 'Europe/Volgograd', 'grocrm'),
            368 => esc_html__( 'Europe/Warsaw', 'grocrm'),
            369 => esc_html__( 'Europe/Zagreb', 'grocrm'),
            370 => esc_html__( 'Europe/Zaporozhye', 'grocrm'),
            371 => esc_html__( 'Europe/Zurich', 'grocrm'),
            372 => esc_html__( 'Indian/Antananarivo', 'grocrm'),
            373 => esc_html__( 'Indian/Chagos', 'grocrm'),
            374 => esc_html__( 'Indian/Christmas', 'grocrm'),
            375 => esc_html__( 'Indian/Cocos', 'grocrm'),
            376 => esc_html__( 'Indian/Comoro', 'grocrm'),
            377 => esc_html__( 'Indian/Kerguelen', 'grocrm'),
            378 => esc_html__( 'Indian/Mahe', 'grocrm'),
            379 => esc_html__( 'Indian/Maldives', 'grocrm'),
            380 => esc_html__( 'Indian/Mauritius', 'grocrm'),
            381 => esc_html__( 'Indian/Mayotte', 'grocrm'),
            382 => esc_html__( 'Indian/Reunion', 'grocrm'),
            383 => esc_html__( 'Pacific/Apia', 'grocrm'),
            384 => esc_html__( 'Pacific/Auckland', 'grocrm'),
            385 => esc_html__( 'Pacific/Bougainville', 'grocrm'),
            386 => esc_html__( 'Pacific/Chatham', 'grocrm'),
            387 => esc_html__( 'Pacific/Chuuk', 'grocrm'),
            388 => esc_html__( 'Pacific/Easter', 'grocrm'),
            389 => esc_html__( 'Pacific/Efate', 'grocrm'),
            390 => esc_html__( 'Pacific/Enderbury', 'grocrm'),
            391 => esc_html__( 'Pacific/Fakaofo', 'grocrm'),
            392 => esc_html__( 'Pacific/Fiji', 'grocrm'),
            393 => esc_html__( 'Pacific/Funafuti', 'grocrm'),
            394 => esc_html__( 'Pacific/Galapagos', 'grocrm'),
            395 => esc_html__( 'Pacific/Gambier', 'grocrm'),
            396 => esc_html__( 'Pacific/Guadalcanal', 'grocrm'),
            397 => esc_html__( 'Pacific/Guam', 'grocrm'),
            398 => esc_html__( 'Pacific/Honolulu', 'grocrm'),
            399 => esc_html__( 'Pacific/Johnston', 'grocrm'),
            400 => esc_html__( 'Pacific/Kiritimati', 'grocrm'),
            401 => esc_html__( 'Pacific/Kosrae', 'grocrm'),
            402 => esc_html__( 'Pacific/Kwajalein', 'grocrm'),
            403 => esc_html__( 'Pacific/Majuro', 'grocrm'),
            404 => esc_html__( 'Pacific/Marquesas', 'grocrm'),
            405 => esc_html__( 'Pacific/Midway', 'grocrm'),
            406 => esc_html__( 'Pacific/Nauru', 'grocrm'),
            407 => esc_html__( 'Pacific/Niue', 'grocrm'),
            408 => esc_html__( 'Pacific/Norfolk', 'grocrm'),
            409 => esc_html__( 'Pacific/Noumea', 'grocrm'),
            410 => esc_html__( 'Pacific/Pago_Pago', 'grocrm'),
            411 => esc_html__( 'Pacific/Palau', 'grocrm'),
            412 => esc_html__( 'Pacific/Pitcairn', 'grocrm'),
            413 => esc_html__( 'Pacific/Pohnpei', 'grocrm'),
            414 => esc_html__( 'Pacific/Port_Moresby', 'grocrm'),
            415 => esc_html__( 'Pacific/Rarotonga', 'grocrm'),
            416 => esc_html__( 'Pacific/Saipan', 'grocrm'),
            417 => esc_html__( 'Pacific/Tahiti', 'grocrm'),
            418 => esc_html__( 'Pacific/Tarawa', 'grocrm'),
            419 => esc_html__( 'Pacific/Tongatapu', 'grocrm'),
            420 => esc_html__( 'Pacific/Wake', 'grocrm'),
            421 => esc_html__( 'Pacific/Wallis', 'grocrm'),
        ];
    }
    
    public function getCountries() {
        return [
            1 => esc_html__( 'Afghanistan', 'grocrm'),
            2 => esc_html__( 'Africa - North', 'grocrm'),
            3 => esc_html__( 'Albania', 'grocrm'),
            4 => esc_html__( 'Algeria', 'grocrm'),
            5 => esc_html__( 'Andorra', 'grocrm'),
            6 => esc_html__( 'Angola', 'grocrm'),
            7 => esc_html__( 'Antigua and Barbuda', 'grocrm'),
            8 => esc_html__( 'Antilles', 'grocrm'),
            9 => esc_html__( 'Argentina', 'grocrm'),
            10 => esc_html__( 'Armenia', 'grocrm'),
            11 => esc_html__( 'Australia', 'grocrm'),
            12 => esc_html__( 'Austria', 'grocrm'),
            13 => esc_html__( 'Azerbaijan', 'grocrm'),
            14 => esc_html__( 'Bahamas', 'grocrm'),
            15 => esc_html__( 'Bahrain', 'grocrm'),
            16 => esc_html__( 'Bangladesh', 'grocrm'),
            17 => esc_html__( 'Barbados', 'grocrm'),
            18 => esc_html__( 'Belarus', 'grocrm'),
            19 => esc_html__( 'Belgium', 'grocrm'),
            20 => esc_html__( 'Belize', 'grocrm'),
            21 => esc_html__( 'Benin', 'grocrm'),
            22 => esc_html__( 'Bhutan', 'grocrm'),
            23 => esc_html__( 'Bolivia', 'grocrm'),
            24 => esc_html__( 'Bosnia and Herzegovina', 'grocrm'),
            25 => esc_html__( 'Botswana', 'grocrm'),
            26 => esc_html__( 'Brazil', 'grocrm'),
            27 => esc_html__( 'Brunei', 'grocrm'),
            28 => esc_html__( 'Bulgaria', 'grocrm'),
            29 => esc_html__( 'Burkina Faso', 'grocrm'),
            30 => esc_html__( 'Burundi', 'grocrm'),
            31 => esc_html__( 'Cambodia', 'grocrm'),
            32 => esc_html__( 'Cameroon', 'grocrm'),
            33 => esc_html__( 'Canada', 'grocrm'),
            34 => esc_html__( 'Cape Verde', 'grocrm'),
            35 => esc_html__( 'Cayman Islands', 'grocrm'),
            36 => esc_html__( 'Central African Republic', 'grocrm'),
            37 => esc_html__( 'Chad', 'grocrm'),
            38 => esc_html__( 'Chile', 'grocrm'),
            39 => esc_html__( 'China', 'grocrm'),
            40 => esc_html__( 'Colombia', 'grocrm'),
            41 => esc_html__( 'Comoros', 'grocrm'),
            42 => esc_html__( 'Congo', 'grocrm'),
            43 => esc_html__( 'Costa Rica', 'grocrm'),
            44 => esc_html__( 'Croatia', 'grocrm'),
            45 => esc_html__( 'Cuba', 'grocrm'),
            46 => esc_html__( 'Cyprus', 'grocrm'),
            47 => esc_html__( 'Czech Republic', 'grocrm'),
            48 => esc_html__( 'Democratic Republic of the Congo', 'grocrm'),
            49 => esc_html__( 'Denmark', 'grocrm'),
            50 => esc_html__( 'Djibouti', 'grocrm'),
            51 => esc_html__( 'Dominica', 'grocrm'),
            52 => esc_html__( 'Dominican Republic', 'grocrm'),
            53 => esc_html__( 'Ecuador', 'grocrm'),
            54 => esc_html__( 'Egypt', 'grocrm'),
            55 => esc_html__( 'El Salvador', 'grocrm'),
            56 => esc_html__( 'Equatorial Guinea', 'grocrm'),
            57 => esc_html__( 'Eritrea', 'grocrm'),
            58 => esc_html__( 'Estonia', 'grocrm'),
            59 => esc_html__( 'Ethiopia', 'grocrm'),
            60 => esc_html__( 'Fiji', 'grocrm'),
            61 => esc_html__( 'Finland', 'grocrm'),
            62 => esc_html__( 'France', 'grocrm'),
            63 => esc_html__( 'Gabon', 'grocrm'),
            64 => esc_html__( 'Gambia', 'grocrm'),
            65 => esc_html__( 'Georgia', 'grocrm'),
            66 => esc_html__( 'Germany', 'grocrm'),
            67 => esc_html__( 'Ghana', 'grocrm'),
            68 => esc_html__( 'Greece', 'grocrm'),
            69 => esc_html__( 'Grenada', 'grocrm'),
            70 => esc_html__( 'Guadeloupe', 'grocrm'),
            71 => esc_html__( 'Guatemala', 'grocrm'),
            72 => esc_html__( 'Guinea', 'grocrm'),
            73 => esc_html__( 'Guinea-Bissau', 'grocrm'),
            74 => esc_html__( 'Guyana', 'grocrm'),
            75 => esc_html__( 'Haiti', 'grocrm'),
            76 => esc_html__( 'Hong Kong', 'grocrm'),
            77 => esc_html__( 'Hungary', 'grocrm'),
            78 => esc_html__( 'Iceland', 'grocrm'),
            79 => esc_html__( 'India', 'grocrm'),
            80 => esc_html__( 'Indonesia', 'grocrm'),
            81 => esc_html__( 'Iran', 'grocrm'),
            82 => esc_html__( 'Iraq', 'grocrm'),
            83 => esc_html__( 'Ireland', 'grocrm'),
            84 => esc_html__( 'Israel', 'grocrm'),
            85 => esc_html__( 'Italy', 'grocrm'),
            86 => esc_html__( 'Ivory Coast', 'grocrm'),
            87 => esc_html__( 'Jamaica', 'grocrm'),
            88 => esc_html__( 'Japan', 'grocrm'),
            89 => esc_html__( 'Jordan', 'grocrm'),
            90 => esc_html__( 'Kazakhstan', 'grocrm'),
            91 => esc_html__( 'Kenya', 'grocrm'),
            92 => esc_html__( 'Kosovo', 'grocrm'),
            93 => esc_html__( 'Kuwait', 'grocrm'),
            94 => esc_html__( 'Kyrgyzstan', 'grocrm'),
            95 => esc_html__( 'Laos', 'grocrm'),
            96 => esc_html__( 'Latvia', 'grocrm'),
            97 => esc_html__( 'Lebanon', 'grocrm'),
            98 => esc_html__( 'Lesotho', 'grocrm'),
            99 => esc_html__( 'Liberia', 'grocrm'),
            100 => esc_html__( 'Libya', 'grocrm'),
            101 => esc_html__( 'Liechtenstein', 'grocrm'),
            102 => esc_html__( 'Lithuania', 'grocrm'),
            103 => esc_html__( 'Luxembourg', 'grocrm'),
            104 => esc_html__( 'Macau', 'grocrm'),
            105 => esc_html__( 'Macedonia', 'grocrm'),
            106 => esc_html__( 'Madagascar', 'grocrm'),
            107 => esc_html__( 'Malawi', 'grocrm'),
            108 => esc_html__( 'Malaysia', 'grocrm'),
            109 => esc_html__( 'Maldives', 'grocrm'),
            110 => esc_html__( 'Mali', 'grocrm'),
            111 => esc_html__( 'Malta', 'grocrm'),
            112 => esc_html__( 'Mauritania', 'grocrm'),
            113 => esc_html__( 'Mauritius', 'grocrm'),
            114 => esc_html__( 'Mauritius', 'grocrm'),
            115 => esc_html__( 'Mexico', 'grocrm'),
            116 => esc_html__( 'Moldova', 'grocrm'),
            117 => esc_html__( 'Monaco', 'grocrm'),
            118 => esc_html__( 'Mongolia', 'grocrm'),
            119 => esc_html__( 'Montenegro', 'grocrm'),
            120 => esc_html__( 'Morocco', 'grocrm'),
            121 => esc_html__( 'Mozambique', 'grocrm'),
            122 => esc_html__( 'Myanmar', 'grocrm'),
            123 => esc_html__( 'Namibia', 'grocrm'),
            124 => esc_html__( 'Nepal', 'grocrm'),
            125 => esc_html__( 'Netherlands', 'grocrm'),
            126 => esc_html__( 'Netherlands Antilles', 'grocrm'),
            127 => esc_html__( 'New Zealand', 'grocrm'),
            128 => esc_html__( 'Nicaragua', 'grocrm'),
            129 => esc_html__( 'Niger', 'grocrm'),
            130 => esc_html__( 'Nigeria', 'grocrm'),
            131 => esc_html__( 'North Korea', 'grocrm'),
            132 => esc_html__( 'Norway', 'grocrm'),
            133 => esc_html__( 'Oman', 'grocrm'),
            134 => esc_html__( 'Pakistan', 'grocrm'),
            135 => esc_html__( 'Panama', 'grocrm'),
            136 => esc_html__( 'Papua New Guinea', 'grocrm'),
            137 => esc_html__( 'Paraguay', 'grocrm'),
            138 => esc_html__( 'Peru', 'grocrm'),
            139 => esc_html__( 'Philippines', 'grocrm'),
            140 => esc_html__( 'Poland', 'grocrm'),
            141 => esc_html__( 'Portugal', 'grocrm'),
            142 => esc_html__( 'Puerto Rico', 'grocrm'),
            143 => esc_html__( 'Qatar', 'grocrm'),
            144 => esc_html__( 'Romania', 'grocrm'),
            145 => esc_html__( 'Russia', 'grocrm'),
            146 => esc_html__( 'Rwanda', 'grocrm'),
            147 => esc_html__( 'Saint Kitts and Nevis', 'grocrm'),
            148 => esc_html__( 'Saint Lucia', 'grocrm'),
            149 => esc_html__( 'Saint Vincent and the Grenadines', 'grocrm'),
            150 => esc_html__( 'San Marino', 'grocrm'),
            151 => esc_html__( 'Sao Tome and Principe', 'grocrm'),
            152 => esc_html__( 'Saudi Arabia', 'grocrm'),
            153 => esc_html__( 'Scotland', 'grocrm'),
            154 => esc_html__( 'Senegal', 'grocrm'),
            155 => esc_html__( 'Serbia', 'grocrm'),
            156 => esc_html__( 'Seychelles', 'grocrm'),
            157 => esc_html__( 'Sierra Leone', 'grocrm'),
            158 => esc_html__( 'Singapore', 'grocrm'),
            159 => esc_html__( 'Slovakia', 'grocrm'),
            160 => esc_html__( 'Slovenia', 'grocrm'),
            161 => esc_html__( 'Somalia', 'grocrm'),
            162 => esc_html__( 'South Africa', 'grocrm'),
            163 => esc_html__( 'South Korea', 'grocrm'),
            164 => esc_html__( 'South Sudan', 'grocrm'),
            165 => esc_html__( 'Spain', 'grocrm'),
            166 => esc_html__( 'Sri Lanka', 'grocrm'),
            167 => esc_html__( 'Sudan', 'grocrm'),
            168 => esc_html__( 'Surivalue', 'grocrm'),
            169 => esc_html__( 'Swaziland', 'grocrm'),
            170 => esc_html__( 'Sweden', 'grocrm'),
            171 => esc_html__( 'Switzerland', 'grocrm'),
            172 => esc_html__( 'Syria', 'grocrm'),
            173 => esc_html__( 'Taiwan', 'grocrm'),
            174 => esc_html__( 'Tajikistan', 'grocrm'),
            175 => esc_html__( 'Tanzania', 'grocrm'),
            176 => esc_html__( 'Thailand', 'grocrm'),
            177 => esc_html__( 'Timor-Leste (East Timor)', 'grocrm'),
            178 => esc_html__( 'Togo', 'grocrm'),
            179 => esc_html__( 'Trinidad and Tobago', 'grocrm'),
            180 => esc_html__( 'Tunisia', 'grocrm'),
            181 => esc_html__( 'Turkey', 'grocrm'),
            182 => esc_html__( 'Turkmenistan', 'grocrm'),
            183 => esc_html__( 'Turks and Caicos Islands', 'grocrm'),
            184 => esc_html__( 'Uganda', 'grocrm'),
            185 => esc_html__( 'Ukraine', 'grocrm'),
            186 => esc_html__( 'United Arab Emirates', 'grocrm'),
            187 => esc_html__( 'United Kingdom', 'grocrm'),
            188 => esc_html__( 'United States', 'grocrm'),
            189 => esc_html__( 'Uruguay', 'grocrm'),
            190 => esc_html__( 'US Virgin Islands', 'grocrm'),
            191 => esc_html__( 'Uzbekistan', 'grocrm'),
            192 => esc_html__( 'Vatican City', 'grocrm'),
            193 => esc_html__( 'Venezuela', 'grocrm'),
            194 => esc_html__( 'Vietnam', 'grocrm'),
            195 => esc_html__( 'Yemen', 'grocrm'),
            196 => esc_html__( 'Zambia', 'grocrm'),
            197 => esc_html__( 'Zimbabwe', 'grocrm'),
        ];
    }
    
    public function getTypes() {
        $args = [
            'headers' => [
                'Authorization' => 'Token '.$this->token,
            ]
        ];
        
        $url = self::BASE_URL."contacts/types";
        
        $response = wp_remote_get($url, $args);
        $statusCode = $response["response"]["code"];
        $body = $response["body"];
        $bodyArray = json_decode($body, true);
        
        if ($statusCode == 200) {
            return json_decode($body, true);
        } elseif (isset($bodyArray["message"])) {
            throw new \Exception($bodyArray["message"], $statusCode);
        } else {
            throw new \Exception("An error has occured. Please try again later.", $statusCode);
        }
    }
    
    public function createContact($parameters) {
        $args = [
            'headers' => [
                'Content-Type' => 'application/json',
                'Authorization' => 'Token '.$this->token,
            ],
            'body' => json_encode($parameters),
        ];
        
        $url = self::BASE_URL."contacts";

        $response = wp_remote_post($url, $args);
        $statusCode = $response["response"]["code"];
        $body = $response["body"];
        $bodyArray = json_decode($body, true);
        
        if ($statusCode == 201) {
            return true;
        } elseif (isset($bodyArray["message"])) {
            throw new \Exception($bodyArray["message"], $statusCode);
        } else {
            throw new \Exception("An error has occured. Please try again later.", $statusCode);
        }
    }
}